package com.google.kobatokokoa0429;

import com.google.kobatokokoa0429.Block.BlockCable;
import com.google.kobatokokoa0429.Block.BlockKobato;
import com.google.kobatokokoa0429.Block.BlockManatite;
import com.google.kobatokokoa0429.Block.BlockWand;
import com.google.kobatokokoa0429.Entity.EntityBarret;
import com.google.kobatokokoa0429.GUI.GuiHandler;
import com.google.kobatokokoa0429.Handler.ManataitoOreGenerator;
import com.google.kobatokokoa0429.Item.ItemManatite;
import com.google.kobatokokoa0429.Item.ItemWand;
import com.google.kobatokokoa0429.Item.ItemWandCore;
import com.google.kobatokokoa0429.Item.ItemWandStick;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;

@Mod(modid = MeguminMOD.MOD_ID, version = MeguminMOD.version, useMetadata = true)

public class MeguminMOD {

	public static final String MOD_ID = "MeguminMod";
	public static final String version = "1.0.0";
	public static final String Domein = "meguminmod";

	public static final CreativeTabs tabMeguminMOD = new tabMegumin();

	@Mod.Instance(MOD_ID) //MODのインスタンス

	public static MeguminMOD INSTANCE;

	public static final int GUI_ID = 1;

    @Mod.Metadata
    public static ModMetadata metadata; //Modの情報を格納する。 mcmod.infoの上位互換

    public static ToolMaterial manataito  = EnumHelper.addToolMaterial("manataito", 0, 114, 5.0F, 5996.0F, 10);

	public static Block blockWand = new BlockWand();
	public static Block blockMatatite = new BlockManatite();

	public static Block blockkobato = new BlockKobato();
	public static Block blockcable = new BlockCable();

	public static Item itemManatite = new ItemManatite();
	public static Item itemWandStick = new ItemWandStick();
	public static Item itemWandCore = new ItemWandCore();
	public static Item itemWand = new ItemWand();

	@SidedProxy(clientSide = "com.google.kobatokokoa0429.ClientProxy", serverSide = "com.google.kobatokokoa0429.CommonProxy")
	public static CommonProxy proxy;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {





		// Blockの登録
		GameRegistry.registerBlock(blockWand, "blockTue");
		GameRegistry.registerBlock(blockMatatite, "blockMatatite");


		GameRegistry.registerBlock(blockkobato, "blockKobato");
		GameRegistry.registerBlock(blockcable, "blockcable");

		// Itemの登録
		GameRegistry.registerItem(itemWand, "itemWand");
		GameRegistry.registerItem(itemManatite, "itemManatite");
		GameRegistry.registerItem(itemWandStick, "itemWandStick");
		GameRegistry.registerItem(itemWandCore, "itemWandCore");

        //PreInitでMetadataの情報を読み込む
        loadMeta();

	}

	@EventHandler
	public void init(FMLInitializationEvent event) {

		// エンティティの登録
		EntityRegistry.registerModEntity(EntityBarret.class, "villagerCannon.villagerHead", 170, this, 128, 5, true);

		// 鉱石生成
		GameRegistry.registerWorldGenerator(new ManataitoOreGenerator(), 0);

		// レシピ登録
		GameRegistry.addShapelessRecipe(new ItemStack(MeguminMOD.itemWand), MeguminMOD.itemWandStick,MeguminMOD.itemWandCore);
		GameRegistry.addRecipe(new ItemStack(MeguminMOD.itemWandStick), " XY", "XYX", "YX ", 'Y', Items.stick, 'X',Items.string);
		GameRegistry.addRecipe(new ItemStack(MeguminMOD.itemWandStick), " XY", "XYX", "YX ", 'Y', Items.stick, 'X',Items.string);
		GameRegistry.addRecipe(new ItemStack(MeguminMOD.itemWandCore), "XXX", " ZY", "XXY", 'X', Items.stick, 'Y',Items.gold_ingot, 'Z', MeguminMOD.itemManatite);

		// TileEntityの登録
		proxy.registerTileEntity();

		// GUIの登録
		NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());

	}

	 private void loadMeta(){
	        metadata.authorList.add("kokoa");
	        metadata.modId = MOD_ID;
	        metadata.name = MOD_ID;
	        metadata.version = version;
	        metadata.description = "こばとかわいい";
	        //これをfalseにしておかないと、ModMetadataが読み込まれない
	        metadata.autogenerated = false;
	    }

}